version: '2'
services:
  basea:

    build: ./base_a
    command: gunicorn -c gunicorn.conf base_a.wsgi
    volumes:
      - ./base_a:/base_a
    ports:
      - "8000:8000"

    
  baseb:
    build: ./base_b
    command: gunicorn -c gunicorn.conf base_b.wsgi
    volumes:
      - ./base_b:/base_b
    ports:
      - "8080:8080"


  nginx:
    build: ./nginx
    depends_on:
      - basea
      - baseb
    command: nginx -g "daemon off;"
    ports:
      - "80:80"