version: '2'
services:
  
  mongo:
    image: mongo
    hostname: mongo
    restart: on-failure
    container_name: mongo
    volumes:
      - /data/db:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

  basea:
    build: ./base_a
    command: gunicorn -c gunicorn.conf base_a.wsgi
    volumes:
      - ./base_a:/base_a
    ports:
      - "8000:8000"

    
  baseb:
    build: ./base_b
    command: gunicorn -c gunicorn.conf base_b.wsgi
    volumes:
      - ./base_b:/base_b
    ports:
      - "8080:8080"
  
  basec:
    build:
      context: ./base_c
    volumes:
      - ./base_c:/base_c
    depends_on:
      - mongo
    links:
      - mongo
    expose:
      - 5000
    ports:
      - 5000:5000

  nginx:
    build: ./nginx
    depends_on:
      - basea
      - baseb
      - basec
    command: nginx -g "daemon off;"
    ports:
      - "80:80"