version: '2'
services:
  base_a:

    build: ./base_a
    command: gunicorn -c gunicorn.conf base_a.wsgi
    volumes:
      - ./base_a:/base_a
    ports:
      - "8000:8000"


  nginx:
    build: ./nginx
    depends_on:
      - base_a
    command: nginx -g "daemon off;"

    ports:
      - "80:80"