version: '2.4'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 8888:80
    volumes:
      - ./base_a:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
  python:
    container_name: python
    build: ./docker/python
    volumes:
      - ./base_a:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    hostname: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=mypassword
       - MYSQL_DATABASE=bureau
       - MYSQL_USER=bureau
       - MYSQL_PASSWORD=bureau
    volumes:
      - mysql-bureau:/var/lib/mysql

volumes:
  mysql-bureau:
