version: '2.4'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 8888:80
    volumes:
      - ./base_a:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
  python:
    container_name: python
    build: ./docker/python
    volumes:
      - ./base_a:/var/www/html
    working_dir: /var/www/html
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=bureau
      - POSTGRES_PASSWORD=bureau
      - POSTGRES_DB=bureau
    volumes:
      - postgres-bureau:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  postgres-bureau:
