# Generated by Django 2.1 on 2018-11-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bem', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='divida',
            name='pessoa',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='address',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='name',
            new_name='renda',
        ),
        migrations.DeleteModel(
            name='Divida',
        ),
        migrations.AddField(
            model_name='bem',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='base_b.Pessoa'),
        ),
    ]
